### ISSUE TITLE
improve Login module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1626]
Here are some minor issues on the Login page we could resolve.

## TODO

- [ ] In the upper right corner of the landing page, remove the Settings button.
- [ ] Landing page logo is slightly smaller.
- [ ] Removing the sample login from the landing page.
- [ ] Default account password should be entered by default on the landing page, so users could log in directly.
- [ ] Spacing between "How to change default account and password" and the login button and password input box on the landing page is too large.

**Comment by iamayushdas** [comment]
Assign this to me @juzhiyuan

**Comment by juzhiyuan** [comment]
thanks, and you could resolve those 2 issues first :)

**Comment by iamayushdas** [comment]
> Here are some minor issues on the Login page we could resolve.
> 
> ## TODO
> * [x]  In the upper right corner of the landing page, remove the Settings button.
> * [x]  Landing page logo is slightly smaller.
> * [ ]  Removing the sample login from the landing page.
> * [ ]  Default account password should be entered by default on the landing page, so users could log in directly.
> * [ ]  Spacing between "How to change default account and password" and the login button and password input box on the landing page is too large.

#1635
