### ISSUE TITLE
improve Route module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1628]
Here are some minor issues on the Route page we could resolve.

## TODO

- [ ] List page, search area field, supplement Placeholder.
- [ ] Create routing page, step 1, form should be aligned to the left, not centered.
- [ ] Create routing page, title remove spaces.

**Comment by qian0817** [comment]
@juzhiyuan Can I work on this?

**Comment by juzhiyuan** [comment]
Sure

**Comment by qian0817** [comment]
@juzhiyuan this issue can be closed
