### ISSUE TITLE
improve Consumer module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1630]
Here are some minor issues on the Consumer page we could resolve.

## TODO

- [ ] search area, using Table's own, using fuzzy search.
- [ ] List page title section, add description: Consumer (Consumer) is XXX.
- [ ] Create page, title: Create Consumer, not `Create Consumer`.
- [ ] Create page, step one, name input box, Placeholder remove spaces.
- [ ] Create page, step one, description under Name input box: consumer name needs to be globally unique; 
- [ ] Create/edit/delete successfully prompt, do not include spaces.
- [ ] list page, add enabled plugin fields, wrap them in tags for display.
- [ ] Edit mode, the title needs to be changed to: Edit Consumer.

**Comment by batman-ezio** [comment]
@juzhiyuan  what's the differences in #3 . they looks the same

**Comment by juzhiyuan** [comment]
#3?

**Comment by qian0817** [comment]
@juzhiyuan task 3 `Create page, title: Create Consumer, not Create Consumer.`also confused me

**Comment by juzhiyuan** [comment]
ok, I mean we need to remove the space in Chinese: `创建 消费者` to `Create Consumer` 🤔
