### ISSUE TITLE
improve Plugin & Plugin Editor & Meta Raw Data Editor module

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1631]
Here are some minor issues on the Plugin & Plugin Editor & Meta Raw Data Editor page we could resolve.

## Plugin TODO

- [ ] Search area, using Table's own, using fuzzy search.
- [ ] page title not internationalized: configure global plugins/Configure Global Plugin.
- [ ] Add icon for Plugin Marketplace plugins.
- [ ] list page top title, add description: list of enabled plugins.
- [ ] list page, edit button in action area modified to: `配置/Configure`.

## Plugin Editor

- [ ] Some Auth plugins do not need to be configured, in the Data Editor, to disable the input of content.
- [ ] The button is not internationalized.
- [ ] Document button fits too close to JSON button.
- [ ] JSONSchema checks for error messages, which can be divided into: error message + view details.
- [ ] CodeMirror code error highlighting.

## Meta Raw data editor (Route List page)
- [ ] Button not internationalized.
- [ ] layout needs to be adjusted, with additional scrolling axes.

**Comment by iamayushdas** [comment]
is there any exact icon to be chosen? in 
* [ ]  Add icon for Plugin Marketplace plugins.

@juzhiyuan

**Comment by iamayushdas** [comment]
Assign this to me. I am working on this. @juzhiyuan

**Comment by iamayushdas** [comment]
> Here are some minor issues on the Plugin & Plugin Editor & Meta Raw Data Editor page we could resolve.
> 
> ## Plugin TODO
> * [ ]  Search area, using Table's own, using fuzzy search.
> * [ ]  page title not internationalized: configure global plugins/Configure Global Plugin.
> * [ ]  Add icon for Plugin Marketplace plugins.
> * [x]  list page top title, add description: list of enabled plugins.
> * [x]  list page, edit button in action area modified to: `配置/Configure`.
> 
> ## Plugin Editor
> * [ ]  Some Auth plugins do not need to be configured, in the Data Editor, to disable the input of content.
> * [ ]  The button is not internationalized.
> * [ ]  Document button fits too close to JSON button.
> * [ ]  JSONSchema checks for error messages, which can be divided into: error message + view details.
> * [ ]  CodeMirror code error highlighting.
> 
> ## Meta Raw data editor (Route List page)
> * [ ]  Button not internationalized.
> * [ ]  layout needs to be adjusted, with additional scrolling axes.

![screencapture-192-168-43-234-8000-plugin-list-2021-03-24-22_13_55](https://user-images.githubusercontent.com/40708551/112351267-bebc0e80-8cef-11eb-9a04-e46a23cd257b.png)
![screencapture-192-168-43-234-8000-plugin-list-2021-03-24-22_13_39](https://user-images.githubusercontent.com/40708551/112351277-c11e6880-8cef-11eb-9629-9c711be8ac96.png)

**Comment by juzhiyuan** [comment]
> is there any exact/specific icon to be chosen? in
> 
> * [ ]   Add icon for Plugin Marketplace plugins.
> 
> @juzhiyuan

I'm back, actually, no for now 🤔

**Comment by juzhiyuan** [comment]
cc @LiteSun @bzp2010 @guoqqqi to review this PR, thx
