### ISSUE TITLE
improve some minor issues

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1632]
Here are some minor issues on the Login page we could resolve.

## TODO
- [ ] Left icon replacement. @LiteSun 
- [ ] Extracting Table as a separate component for reuse in various modules.
- [ ] APISIX plugin type change.
- [ ] GitHub hyperlink (icon) added to Header section.

**Comment by iamayushdas** [comment]
Would like to work on this Assign this to me @juzhiyuan

**Comment by juzhiyuan** [comment]
as for the first one, @LiteSun will do that.

**Comment by iamayushdas** [comment]
> Here are some minor issues on the Login page we could resolve.
> 
> ## TODO
> * [ ]  Left icon replacement. @LiteSun
> * [ ]  Extracting Table as a separate component for reuse in various modules.
> * [ ]  APISIX plugin type change.
> * [ ]  GitHub hyperlink (icon) added to Header section.

could please brief 3rd todo?

**Comment by juzhiyuan** [comment]
oh yes, we have 40+ plugins here[1], and take `basic-auth`[2] as an example, you could see it's belonged to `auth` type[3].

We have other plugins that without `type` filed or just use the `default` type field, like this one[4], we need to update them. You could find all `type` here[5]:

![image](https://user-images.githubusercontent.com/2106987/111891027-1de8fd00-8a2a-11eb-83f4-81c7f307ad7f.png)

Please use `lowercase` as `type`.

[1] https://github.com/apache/apisix/tree/master/apisix/plugins
[2] https://github.com/apache/apisix/blob/master/apisix/plugins/basic-auth.lua
[3] https://github.com/apache/apisix/blob/master/apisix/plugins/basic-auth.lua#L53
[4] https://github.com/apache/apisix/blob/master/apisix/plugins/kafka-logger.lua#L60
[5] http://apisix.apache.org/docs/apisix/plugins/batch-requests

**Comment by iamayushdas** [comment]
Here
> [5] http://apisix.apache.org/docs/apisix/plugins/batch-requests
i am not able to find `type` for plugin that i have to put in local _M={}
can you please tell me more on what type will be used in transformation plugins.,i am lil confused

**Comment by spacewander** [comment]
@juzhiyuan 
Your description of the `type` field is wrong!
It is nothing about the category in the documentation.

The `auth` type in the APISIX has a special meaning (although this name is quite confusing) - to mark a plugin should be interacted with the consumer.

I have explained the same thing many times:
https://github.com/apache/apisix-dashboard/issues/1174#issuecomment-754508964
https://github.com/apache/apisix-dashboard/issues/1387#issuecomment-772592212

**Comment by juzhiyuan** [comment]
😳 then how do add a category for every plugin? I have read through some plugins' codes and only see the `type` field here.

https://github.com/apache/apisix/blob/master/apisix/plugins/basic-auth.lua#L53

**Comment by iamayushdas** [comment]
> 😳 then how do add a category for every plugin? I have read through some plugins' codes and only see the `type` field here.
> 
> 
> 
> https://github.com/apache/apisix/blob/master/apisix/plugins/basic-auth.lua#L53

Exactly this is confusing for me too

**Comment by spacewander** [comment]
It is all about the doc.
There is no formal standard to determine which category a plugin will belong to yet.

**Comment by juzhiyuan** [comment]
all right, then what `type` filed does? 🤔 I couldn't find its description.

[1] https://apisix.apache.org/docs/apisix/architecture-design/plugin

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/blob/master/docs/en/latest/plugin-develop.md#schema-and-check

**Comment by juzhiyuan** [comment]
Thanks!

After read through this description about how to write a plugin, `When we set the type of plugin to auth, it means that this plugin is an authentication plugin.` does this mean the type field is only used with `Auth` plugins now? could we set `type = security to a plugin?

**Comment by spacewander** [comment]
> `does this mean the type field is only used with Auth plugins now`?

Yes.

> could we set type = security to a plugin

Why? This is meaningless.

**Comment by spacewander** [comment]
The type and the category are two different things.
If you want to mark a plugin with a category, better to introduce a new field called "category".

**Comment by juzhiyuan** [comment]
🤔 not sure ...  if `type` is `Only` used with `Auth` plugin, why not use `is_auth_plugin` to replace `type = auth`?

**Comment by spacewander** [comment]
> does this mean the type field is only used with Auth plugins now

To be correct, it is plugins need to work with consumers, not plugins used to authenticate.
A plugin used to authenticate can be used with or without a consumer.

**Comment by juzhiyuan** [comment]
all right, @iamayushdas Hi, this issue may get pending due to we have something need to discuss. 🤔  Please take other issues 🐱

**Comment by iamayushdas** [comment]
@juzhiyuan in 4th task you mean to add a github icon next to the language change icon?

**Comment by juzhiyuan** [comment]
ya

**Comment by juzhiyuan** [comment]
and link it to `https://apisix.apache.org`

**Comment by iamayushdas** [comment]
Here are some minor issues on the Login page we could resolve.
 
 ## TODO
 * [ ]  Left icon replacement. @LiteSun
 * [ ]  Extracting Table as a separate component for reuse in various modules.
 * [ ]  APISIX plugin type change.
 * [x]  GitHub hyperlink (icon) added to Header section.

**Comment by iamayushdas** [comment]
## TODO
 * [ ]  Left icon replacement. @LiteSun
 * [ ]  Extracting Table as a separate component for reuse in various modules.
 * [ ]  APISIX plugin type change.
 * [x]  GitHub hyperlink (icon) added to Header section.
 
![screencapture-172-20-10-3-8000-user-login-2021-03-23-09_08_39](https://user-images.githubusercontent.com/40708551/112090245-376c7f00-8bb9-11eb-9e10-3e0edc3f2c60.png)

**Comment by juzhiyuan** [comment]
good good
