### ISSUE TITLE
sync with the latest schema from APISIX 2.7

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#2015]
The Apache APISIX 2.7 has been released, this PR https://github.com/apache/apisix-dashboard/pull/1999/files contains the differences from schema.json.

**TODO**
- [ ] Plugin: support all missing fields or newly added plugins in the Web
- [ ] API: support all missing fields in the Web

**Comment by Baoyuantop** [comment]
Hi, I can help solve this issue.

**Comment by Baoyuantop** [comment]
According to the comparison of schema.json, I summarized the following work

Web

- [ ] supports Service Discovery when creating an upstream #1977 
- [ ] edit sins type in SSL
- [ ] add stream route #1986

Plugin

- [ ] add new plugin client-control
- [ ] delete auth_value in echo
- [ ]  edit ext-plugin-post-req
- [ ]  edit ext-plugin-pre-req
- [ ]  add nodelay in limit-req
- [ ]  edit mqtt-proxy
- [ ]  add append_query_string in redirect
- [ ]  edit traffic-split

**Comment by Baoyuantop** [comment]
In addition to this, there is another problem. I found a modification to the sni verification rule in SSL in the [schema.json](https://github.com/apache/apisix-dashboard/pull/1999/files#diff-5fadf7c6b5b550d0a97075c3ddeaf29028204cd60da2660c6a1e1c72b4bbd0edR1340), but I did not find information about it in the [APISIX admin API](https://apisix.apache.org/docs/apisix/admin-api#request-body-parameters-4)

**Comment by juzhiyuan** [comment]
ok, I would prefer supporting the Plugins part in this milestone, other changes are new features IMO.

cc @liuxiran
