### ISSUE TITLE
PluginModule v3

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#480]
## TODO
- [x] icon for plugins
- [x] UI: Category
- [ ] ~Hover Tooltip: desc~ no needed
- [x] Plugin Sort
- [ ] ~Form fields check~ https://github.com/apache/apisix-dashboard/issues/501

**Comment by juzhiyuan** [comment]
cc @LiteSun please set category for plugin orchestration

**Comment by juzhiyuan** [comment]
> plugin orchestration

@LiteSun  https://github.com/apache/apisix-dashboard/issues/490
