### ISSUE TITLE
add e2e test for Upstream

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix-dashboard#642]
Upstream
- [ ] create: long description and  name include common symbols
- [ ] edit:
- [ ] delete:
- [ ] search: full match, partial match, no match
- [ ] big data environment test: upstream operation under more than 200 upstream

related issue #614

**Comment by idbeta** [comment]
hello, assign to me pls.

**Comment by juzhiyuan** [comment]
**TODO**
- [ ] HealthCheck: custom active port https://github.com/apache/apisix-dashboard/pull/1078
